# Generated by Django 4.1.7 on 2023-03-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobs_arquivo_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='arquivo_final',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
